repos:
- repo: local
  hooks:
  - id: forbid-asv-files
    name: Fail when .asv files are present
    entry: "bash -c 'echo \"Error: .asv files are not allowed:\" \"$@\" >&2; exit 1'"
    language: system
    files: \.asv$
    pass_filenames: true
